CREATE TABLE tb_subscriptions
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 varchar(255)   NOT NULL,
    description          varchar(255),
    value                numeric(10, 2) NOT NULL,

    start_date           DATE           NOT NULL,
    next_payment_date    DATE           NOT NULL,

    active               boolean                 DEFAULT true,
    notify               boolean                 DEFAULT true,
    currency             varchar(3)     NOT NULL DEFAULT 'BRL',
    logo_url             varchar(255),

    id_categories        bigint,
    id_payment_method    bigint,
    id_billing_cycle     bigint,
    id_subscription_type bigint
);

CREATE TABLE tb_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE tb_payment_methods
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE tb_billing_cycles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

CREATE TABLE tb_subscription_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);

ALTER TABLE tb_subscriptions
    ADD FOREIGN KEY (id_categories) REFERENCES tb_categories (id);
ALTER TABLE tb_subscriptions
    ADD FOREIGN KEY (id_payment_method) REFERENCES tb_payment_methods (id);
ALTER TABLE tb_subscriptions
    ADD FOREIGN KEY (id_billing_cycle) REFERENCES tb_billing_cycles (id);
ALTER TABLE tb_subscriptions
    ADD FOREIGN KEY (id_subscription_type) REFERENCES tb_subscription_types (id);