spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      url: ${REDIS_URL}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  docker:
    compose:
      enabled: false
logging:
  level:
    root: WARN
    dev.guilhermeluan: INFO
exchange:
  api:
    url: ${EXCHANGE_API_URL}